import assert from "node:assert/strict";
import { mkdtemp, readFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import test from "node:test";
import { AccountStore } from "../src/account-store.js";
import { ModelConfigStore, contextWindowForRoute } from "../src/model-config.js";
import { GEMINI_FLASH_LITE_MODEL, ProviderRegistry, knownModelMetadata } from "../src/provider-registry.js";
import { createReplicatedServer } from "../src/replicated-dispatcher.js";
import { upstreamApiFor } from "../src/upstream-api.js";

async function fixture(){const root=await mkdtemp(path.join(os.tmpdir(),"openai-cc-s45-"));const store=new AccountStore(root);await store.init();const providers=new ProviderRegistry(root);await providers.init();const models=new ModelConfigStore(root,store,providers);await models.init();return{root,store,providers,models};}
async function listen(server:any){await new Promise<void>(r=>server.listen(0,"127.0.0.1",r));const a=server.address();if(!a||typeof a==="string")throw new Error("bad address");return `http://127.0.0.1:${a.port}`;}
async function close(server:any){await new Promise<void>(r=>server.close(()=>r()));}

test("Gemini Flash-Lite metadata and fresh route contexts are capped correctly",async()=>{const f=await fixture();const meta=knownModelMetadata("google",GEMINI_FLASH_LITE_MODEL);assert.equal(meta?.contextWindow,1_048_576);assert.equal(meta?.maxOutputTokens,65_536);const c=f.models.snapshot();assert.equal(contextWindowForRoute(c,"default",f.providers),200_000);assert.equal(contextWindowForRoute(c,"opus",f.providers),200_000);assert.equal(contextWindowForRoute(c,"fable",f.providers),850_000);assert.equal(contextWindowForRoute(c,"sonnet",f.providers),850_000);assert.equal(contextWindowForRoute(c,"haiku",f.providers),850_000);f.store.close();});

test("custom providers persist with stable ids and conservative unknown limits",async()=>{const f=await fixture();const p=await f.providers.createCustom({displayName:"Local OpenAI",baseUrl:"https://example.invalid/v1/",apiStyle:"chat-completions"});assert.match(p.id,/^custom-[a-f0-9]{12}$/);await f.providers.upsertManualModel(p.id,{id:"manual/model",contextWindow:500000,maxOutputTokens:32000});const reloaded=new ProviderRegistry(f.root);await reloaded.init();assert.equal(reloaded.getCustom(p.id)?.baseUrl,"https://example.invalid/v1");assert.equal(reloaded.metadata(p.id,"manual/model")?.contextWindow,500000);assert.equal(reloaded.metadata(p.id,"unknown")?.contextWindow,200000);assert.equal(reloaded.metadata(p.id,"unknown")?.maxOutputTokens,16384);const disk=await readFile(path.join(f.root,"providers.json"),"utf8");assert.equal(/api.?key|secret/i.test(disk),false);f.store.close();});

test("custom /models discovery enriches manual limits and keeps Authorization out of results",async()=>{const f=await fixture();const p=await f.providers.createCustom({displayName:"Discovery",baseUrl:"https://provider.invalid/v1",apiStyle:"chat-completions"});await f.providers.upsertManualModel(p.id,{id:"m1",contextWindow:700000,maxOutputTokens:50000});const account=await f.store.createApiKey({provider:p.id,apiKey:"do-not-expose"});let auth="";const result=await f.providers.discover(account,(async(_u,init)=>{auth=new Headers(init?.headers).get("authorization")||"";return new Response(JSON.stringify({data:[{id:"m1"},{id:"m2"}]}),{status:200});})as typeof fetch);assert.equal(auth,"Bearer do-not-expose");assert.equal(result[0].contextWindow,700000);assert.equal(result[1].contextWindow,200000);assert.equal(JSON.stringify(result).includes("do-not-expose"),false);f.store.close();});

test("custom API style selects Chat Completions or Responses without touching ChatGPT",async()=>{const f=await fixture();const chat=await f.providers.createCustom({displayName:"Chat",baseUrl:"https://chat.invalid/v1",apiStyle:"chat-completions"});const responses=await f.providers.createCustom({displayName:"Responses",baseUrl:"https://responses.invalid/v1",apiStyle:"responses"});assert.equal(upstreamApiFor(chat.id,"m",f.providers),"chat-completions");assert.equal(upstreamApiFor(responses.id,"m",f.providers),"responses");assert.equal(upstreamApiFor("chatgpt","gpt-5.6-terra",f.providers),"responses");f.store.close();});

test("production Gemini Sonnet path carries vision, tools, multi-turn tool results, streaming and output cap",async()=>{const f=await fixture();await f.store.createApiKey({id:"g1",provider:"google",apiKey:"secret"});let captured:any;const server=createReplicatedServer(f.store,f.models,{bindHost:"127.0.0.1",providerRegistry:f.providers,clientFactory:()=>({chat:{completions:{create:async(req:any)=>{captured=req;if(req.stream)return(async function*(){yield{id:"s",choices:[{delta:{content:"ok"}}]};yield{id:"s",choices:[{delta:{},finish_reason:"stop"}],usage:{completion_tokens:1}}})();return{id:"r",choices:[{message:{content:"ok"},finish_reason:"stop"}],usage:{prompt_tokens:10,completion_tokens:1}};}}}})});const base=await listen(server);try{let r=await fetch(base+"/v1/messages",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({model:"sonnet",max_tokens:999999,tools:[{name:"lookup",input_schema:{type:"object",properties:{}}}],messages:[{role:"user",content:[{type:"text",text:"classify"},{type:"image",source:{type:"base64",media_type:"image/png",data:"aGVsbG8="}}]},{role:"assistant",content:[{type:"tool_use",id:"t1",name:"lookup",input:{}}]},{role:"user",content:[{type:"tool_result",tool_use_id:"t1",content:"done"}]}]})});assert.equal(r.status,200);assert.equal(captured.model,GEMINI_FLASH_LITE_MODEL);assert.equal(captured.max_tokens,65536);assert.equal(captured.messages[0].content[1].type,"image_url");assert.equal(captured.messages[1].tool_calls[0].id,"t1");assert.equal(captured.messages[2].role,"tool");r=await fetch(base+"/v1/messages",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({model:"haiku",max_tokens:16,stream:true,messages:[{role:"user",content:"subagent compacted continuation"}]})});assert.equal(r.status,200);assert.match(await r.text(),/message_stop/);}finally{await close(server);}});

test("production custom credential rotation stays provider-local for 401 and 429",async()=>{const f=await fixture();const p=await f.providers.createCustom({displayName:"Rotating",baseUrl:"https://rotate.invalid/v1",apiStyle:"chat-completions"});await f.store.createApiKey({id:"c1",provider:p.id,apiKey:"one"});await f.store.createApiKey({id:"c2",provider:p.id,apiKey:"two"});await f.providers.upsertManualModel(p.id,{id:"m",contextWindow:300000,maxOutputTokens:32000});const cfg=f.models.snapshot();cfg.routes.sonnet={provider:p.id,model:"m",maxOutputTokens:32000};await f.models.update(cfg);const calls:string[]=[];const server=createReplicatedServer(f.store,f.models,{bindHost:"127.0.0.1",providerRegistry:f.providers,clientFactory:(a)=>({chat:{completions:{create:async()=>{calls.push(a.id);if(a.id==="c1")throw Object.assign(new Error("401 token=hidden"),{status:401});return{id:"ok",choices:[{message:{content:"ok"},finish_reason:"stop"}]};}}}})});const base=await listen(server);try{const r=await fetch(base+"/v1/messages",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({model:"sonnet",max_tokens:8,messages:[{role:"user",content:"hi"}]})});assert.equal(r.status,200);assert.deepEqual(calls,["c1","c2"]);assert.equal(f.store.publicGet("c1")?.status,"auth_error");}finally{await close(server);}});


test("DeepSeek Default enforces the recorded 200K effective context before upstream dispatch",async()=>{const f=await fixture();await f.store.createApiKey({id:"z1",provider:"zen",apiKey:"secret"});let calls=0;const server=createReplicatedServer(f.store,f.models,{bindHost:"127.0.0.1",providerRegistry:f.providers,clientFactory:()=>({chat:{completions:{create:async()=>{calls++;return{id:"x",choices:[{message:{content:"unexpected"},finish_reason:"stop"}]};}}}})});const base=await listen(server);try{const response=await fetch(base+"/v1/messages",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({model:"default",max_tokens:8,messages:[{role:"user",content:"x".repeat(730000)}]})});assert.equal(response.status,400);assert.match(await response.text(),/context_window_exceeded/);assert.equal(calls,0);}finally{await close(server);}});

test("Gemini Sonnet accepts long classifier-like traffic beyond 200K while Haiku aliases route as subagents",async()=>{const f=await fixture();await f.store.createApiKey({id:"g1",provider:"google",apiKey:"secret"});const seen:string[]=[];const server=createReplicatedServer(f.store,f.models,{bindHost:"127.0.0.1",providerRegistry:f.providers,clientFactory:()=>({chat:{completions:{create:async(req:any)=>{seen.push(req.model);return{id:"ok",choices:[{message:{content:"ok"},finish_reason:"stop"}],usage:{prompt_tokens:1,completion_tokens:1}};}}}})});const base=await listen(server);try{let response=await fetch(base+"/v1/messages",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({model:"claude-sonnet-5",max_tokens:8,system:"Classify the requested task for Auto Mode.",messages:[{role:"user",content:"x".repeat(730000)}]})});assert.equal(response.status,200);response=await fetch(base+"/v1/messages",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({model:"claude-opus-4-7[1m]",max_tokens:8,messages:[{role:"user",content:"Haiku subagent continuation after compaction"}]})});assert.equal(response.status,200);assert.deepEqual(seen,[GEMINI_FLASH_LITE_MODEL,GEMINI_FLASH_LITE_MODEL]);}finally{await close(server);}});

test("custom Responses provider runs through the production dispatcher with tools and streaming",async()=>{const f=await fixture();const p=await f.providers.createCustom({displayName:"Responses Custom",baseUrl:"https://responses.invalid/v1",apiStyle:"responses"});await f.providers.upsertManualModel(p.id,{id:"resp-model",contextWindow:400000,maxOutputTokens:24000});await f.store.createApiKey({id:"r1",provider:p.id,apiKey:"secret"});const cfg=f.models.snapshot();cfg.routes.sonnet={provider:p.id,model:"resp-model",maxOutputTokens:24000};await f.models.update(cfg);const seen:any[]=[];const server=createReplicatedServer(f.store,f.models,{bindHost:"127.0.0.1",providerRegistry:f.providers,clientFactory:()=>({responses:{create:async(req:any)=>{seen.push(req);if(req.stream)return(async function*(){yield{type:"response.output_text.delta",item_id:"msg",output_index:0,delta:"streamed"};yield{type:"response.completed",response:{id:"resp-stream",usage:{input_tokens:1,output_tokens:1}}};})();return{id:"resp",output:[{type:"message",content:[{type:"output_text",text:"done"}]}],usage:{input_tokens:1,output_tokens:1}};}}})});const base=await listen(server);try{let response=await fetch(base+"/v1/messages",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({model:"sonnet",max_tokens:99999,tools:[{name:"lookup",input_schema:{type:"object",properties:{}}}],messages:[{role:"user",content:"use tool"}]})});assert.equal(response.status,200);assert.equal((await response.json() as any).content[0].text,"done");assert.equal(seen[0].model,"resp-model");assert.equal(seen[0].max_output_tokens,24000);assert.equal(seen[0].tools[0].type,"function");response=await fetch(base+"/v1/messages",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({model:"sonnet",max_tokens:8,stream:true,messages:[{role:"user",content:"stream"}]})});assert.equal(response.status,200);assert.match(await response.text(),/streamed/);}finally{await close(server);}});

test("custom provider routes, credentials and explicit limits survive restart",async()=>{const f=await fixture();const p=await f.providers.createCustom({displayName:"Persistent",baseUrl:"https://persist.invalid/v1",apiStyle:"chat-completions"});await f.providers.upsertManualModel(p.id,{id:"persist-model",contextWindow:610000,maxOutputTokens:31000});await f.store.createApiKey({id:"persist-key",provider:p.id,apiKey:"secret"});const cfg=f.models.snapshot();cfg.routes.opus={provider:p.id,model:"persist-model",maxOutputTokens:31000};await f.models.update(cfg);f.store.close();const store2=new AccountStore(f.root);await store2.init();const providers2=new ProviderRegistry(f.root);await providers2.init();const models2=new ModelConfigStore(f.root,store2,providers2);await models2.init();assert.equal(models2.snapshot().routes.opus.provider,p.id);assert.equal(models2.snapshot().routes.opus.model,"persist-model");assert.equal(models2.contextWindowForRequestedModel("opus"),610000);assert.equal(models2.credentialForRequestedModel("opus")?.id,"persist-key");store2.close();});

test("custom provider 429 rotates only to another credential on the same provider",async()=>{const f=await fixture();const p=await f.providers.createCustom({displayName:"429 Custom",baseUrl:"https://limit.invalid/v1",apiStyle:"chat-completions"});await f.providers.upsertManualModel(p.id,{id:"m",contextWindow:300000,maxOutputTokens:16000});await f.store.createApiKey({id:"l1",provider:p.id,apiKey:"one"});await f.store.createApiKey({id:"l2",provider:p.id,apiKey:"two"});await f.store.createApiKey({id:"g-other",provider:"google",apiKey:"other"});const cfg=f.models.snapshot();cfg.routes.haiku={provider:p.id,model:"m",maxOutputTokens:16000};await f.models.update(cfg);const calls:string[]=[];const server=createReplicatedServer(f.store,f.models,{bindHost:"127.0.0.1",providerRegistry:f.providers,clientFactory:(a)=>({chat:{completions:{create:async()=>{calls.push(a.id);if(a.id==="l1")throw Object.assign(new Error("429 quota"),{status:429});return{id:"ok",choices:[{message:{content:"ok"},finish_reason:"stop"}]};}}}})});const base=await listen(server);try{const response=await fetch(base+"/v1/messages",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({model:"haiku",max_tokens:8,messages:[{role:"user",content:"hi"}]})});assert.equal(response.status,200);assert.deepEqual(calls,["l1","l2"]);assert.equal(f.store.publicGet("l1")?.status,"exhausted");}finally{await close(server);}});

test("Admin custom provider CRUD, manual fallback and credentials keep secrets out of state",async()=>{const f=await fixture();const server=createReplicatedServer(f.store,f.models,{bindHost:"127.0.0.1",providerRegistry:f.providers});const base=await listen(server);try{let response=await fetch(base+"/admin/providers",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({displayName:"Admin Custom",baseUrl:"https://custom.invalid/v1",apiStyle:"responses"})});assert.equal(response.status,201);const provider=await response.json() as any;response=await fetch(base+"/admin/providers/"+provider.id,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({displayName:"Admin Custom 2",baseUrl:"https://custom2.invalid/v1",apiStyle:"chat-completions"})});assert.equal(response.status,200);response=await fetch(base+"/admin/providers/"+provider.id+"/models",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({id:"manual",contextWindow:444000,maxOutputTokens:22222})});assert.equal(response.status,200);response=await fetch(base+"/admin/credentials",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({provider:provider.id,apiKey:"never-return-this"})});assert.equal(response.status,201);const credential=await response.json() as any;assert.equal(JSON.stringify(credential).includes("never-return-this"),false);response=await fetch(base+"/admin/state");const stateText=await response.text();assert.equal(stateText.includes("never-return-this"),false);const state=JSON.parse(stateText);const publicProvider=state.providers.find((x:any)=>x.id===provider.id);assert.equal(publicProvider.baseUrl,"https://custom2.invalid/v1");assert.equal(publicProvider.models[0].contextWindow,444000);response=await fetch(base+"/admin/providers/"+provider.id,{method:"DELETE",headers:{"content-type":"application/json"},body:"{}"});assert.equal(response.status,409);response=await fetch(base+"/admin/credentials/"+credential.id,{method:"DELETE",headers:{"content-type":"application/json"},body:"{}"});assert.equal(response.status,200);response=await fetch(base+"/admin/providers/"+provider.id,{method:"DELETE",headers:{"content-type":"application/json"},body:"{}"});assert.equal(response.status,200);}finally{await close(server);}});
