import assert from "node:assert/strict";
import { mkdtemp, readFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import test from "node:test";
import { AccountStore } from "../src/account-store.js";
import { ModelConfigStore, contextWindowForRoute } from "../src/model-config.js";
import { GEMINI_FLASH_LITE_MODEL, ProviderRegistry, knownModelMetadata } from "../src/provider-registry.js";
import { createReplicatedServer } from "../src/replicated-dispatcher.js";
import { upstreamApiFor } from "../src/upstream-api.js";

async function fixture(){const root=await mkdtemp(path.join(os.tmpdir(),"openai-cc-s45-"));const store=new AccountStore(root);await store.init();const providers=new ProviderRegistry(root);await providers.init();const models=new ModelConfigStore(root,store,providers);await models.init();return{root,store,providers,models};}
async function listen(server:any){await new Promise<void>(r=>server.listen(0,"127.0.0.1",r));const a=server.address();if(!a||typeof a==="string")throw new Error("bad address");return `http://127.0.0.1:${a.port}`;}
async function close(server:any){await new Promise<void>(r=>server.close(()=>r()));}

test("Gemini Flash-Lite metadata and fresh route contexts are capped correctly",async()=>{const f=await fixture();const meta=knownModelMetadata("google",GEMINI_FLASH_LITE_MODEL);assert.equal(meta?.contextWindow,1_048_576);assert.equal(meta?.maxOutputTokens,65_536);const c=f.models.snapshot();assert.equal(contextWindowForRoute(c,"default",f.providers),200_000);assert.equal(contextWindowForRoute(c,"opus",f.providers),200_000);assert.equal(contextWindowForRoute(c,"fable",f.providers),850_000);assert.equal(contextWindowForRoute(c,"sonnet",f.providers),850_000);assert.equal(contextWindowForRoute(c,"haiku",f.providers),850_000);f.store.close();});

test("custom providers persist with stable ids and conservative unknown limits",async()=>{const f=await fixture();const p=await f.providers.createCustom({displayName:"Local OpenAI",baseUrl:"https://example.invalid/v1/",apiStyle:"chat-completions"});assert.match(p.id,/^custom-[a-f0-9]{12}$/);await f.providers.upsertManualModel(p.id,{id:"manual/model",contextWindow:500000,maxOutputTokens:32000});const reloaded=new ProviderRegistry(f.root);await reloaded.init();assert.equal(reloaded.getCustom(p.id)?.baseUrl,"https://example.invalid/v1");assert.equal(reloaded.metadata(p.id,"manual/model")?.contextWindow,500000);assert.equal(reloaded.metadata(p.id,"unknown")?.contextWindow,200000);assert.equal(reloaded.metadata(p.id,"unknown")?.maxOutputTokens,16384);const disk=await readFile(path.join(f.root,"providers.json"),"utf8");assert.equal(/api.?key|secret/i.test(disk),false);f.store.close();});

test("custom /models discovery enriches manual limits and keeps Authorization out of results",async()=>{const f=await fixture();const p=await f.providers.createCustom({displayName:"Discovery",baseUrl:"https://provider.invalid/v1",apiStyle:"chat-completions"});await f.providers.upsertManualModel(p.id,{id:"m1",contextWindow:700000,maxOutputTokens:50000});const account=await f.store.createApiKey({provider:p.id,apiKey:"do-not-expose"});let auth="";const result=await f.providers.discover(account,(async(_u,init)=>{auth=new Headers(init?.headers).get("authorization")||"";return new Response(JSON.stringify({data:[{id:"m1"},{id:"m2"}]}),{status:200});})as typeof fetch);assert.equal(auth,"Bearer do-not-expose");assert.equal(result[0].contextWindow,700000);assert.equal(result[1].contextWindow,200000);assert.equal(JSON.stringify(result).includes("do-not-expose"),false);f.store.close();});

test("custom API style selects Chat Completions or Responses without touching ChatGPT",async()=>{const f=await fixture();const chat=await f.providers.createCustom({displayName:"Chat",baseUrl:"https://chat.invalid/v1",apiStyle:"chat-completions"});const responses=await f.providers.createCustom({displayName:"Responses",baseUrl:"https://responses.invalid/v1",apiStyle:"responses"});assert.equal(upstreamApiFor(chat.id,"m",f.providers),"chat-completions");assert.equal(upstreamApiFor(responses.id,"m",f.providers),"responses");assert.equal(upstreamApiFor("chatgpt","gpt-5.6-terra",f.providers),"responses");f.store.close();});

test("production Gemini Sonnet path carries vision, tools, multi-turn tool results, streaming and output cap",async()=>{const f=await fixture();await f.store.createApiKey({id:"g1",provider:"google",apiKey:"secret"});let captured:any;const server=createReplicatedServer(f.store,f.models,{bindHost:"127.0.0.1",providerRegistry:f.providers,clientFactory:()=>({chat:{completions:{create:async(req:any)=>{captured=req;if(req.stream)return(async function*(){yield{id:"s",choices:[{delta:{content:"ok"}}]};yield{id:"s",choices:[{delta:{},finish_reason:"stop"}],usage:{completion_tokens:1}}})();return{id:"r",choices:[{message:{content:"ok"},finish_reason:"stop"}],usage:{prompt_tokens:10,completion_tokens:1}};}}}})});const base=await listen(server);try{let r=await fetch(base+"/v1/messages",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({model:"sonnet",max_tokens:999999,tools:[{name:"lookup",input_schema:{type:"object",properties:{}}}],messages:[{role:"user",content:[{type:"text",text:"classify"},{type:"image",source:{type:"base64",media_type:"image/png",data:"aGVsbG8="}}]},{role:"assistant",content:[{type:"tool_use",id:"t1",name:"lookup",input:{}}]},{role:"user",content:[{type:"tool_result",tool_use_id:"t1",content:"done"}]}]})});assert.equal(r.status,200);assert.equal(captured.model,GEMINI_FLASH_LITE_MODEL);assert.equal(captured.max_tokens,65536);assert.equal(captured.messages[0].content[1].type,"image_url");assert.equal(captured.messages[1].tool_calls[0].id,"t1");assert.equal(captured.messages[2].role,"tool");r=await fetch(base+"/v1/messages",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({model:"haiku",max_tokens:16,stream:true,messages:[{role:"user",content:"subagent compacted continuation"}]})});assert.equal(r.status,200);assert.match(await r.text(),/message_stop/);}finally{await close(server);}});

test("production custom credential rotation stays provider-local for 401 and 429",async()=>{const f=await fixture();const p=await f.providers.createCustom({displayName:"Rotating",baseUrl:"https://rotate.invalid/v1",apiStyle:"chat-completions"});await f.store.createApiKey({id:"c1",provider:p.id,apiKey:"one"});await f.store.createApiKey({id:"c2",provider:p.id,apiKey:"two"});await f.providers.upsertManualModel(p.id,{id:"m",contextWindow:300000,maxOutputTokens:32000});const cfg=f.models.snapshot();cfg.routes.sonnet={provider:p.id,model:"m",maxOutputTokens:32000};await f.models.update(cfg);const calls:string[]=[];const server=createReplicatedServer(f.store,f.models,{bindHost:"127.0.0.1",providerRegistry:f.providers,clientFactory:(a)=>({chat:{completions:{create:async()=>{calls.push(a.id);if(a.id==="c1")throw Object.assign(new Error("401 token=hidden"),{status:401});return{id:"ok",choices:[{message:{content:"ok"},finish_reason:"stop"}]};}}}})});const base=await listen(server);try{const r=await fetch(base+"/v1/messages",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({model:"sonnet",max_tokens:8,messages:[{role:"user",content:"hi"}]})});assert.equal(r.status,200);assert.deepEqual(calls,["c1","c2"]);assert.equal(f.store.publicGet("c1")?.status,"auth_error");}finally{await close(server);}});
