export function adminPage(csrfToken: string, nonce: string): string {
  const boot = JSON.stringify({ csrfToken }).replace(/</g, "\\u003c");
  return `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>OpenAI-CC Admin</title>
<style nonce="${escapeHtml(nonce)}">
:root{color-scheme:dark;font-family:Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}*{box-sizing:border-box}body{margin:0;background:#0c1016;color:#e8edf4}.shell{max-width:1180px;margin:0 auto;padding:32px 18px 60px}h1{font-size:28px;margin:0 0 6px}h2{font-size:18px;margin:0 0 14px}h3{font-size:15px;margin:0}.sub,.muted{color:#99a6b5}.top{margin-bottom:24px}.panel{background:#151b24;border:1px solid #252e3b;border-radius:14px;padding:18px;margin:14px 0}.overview{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:10px}.metric{background:#0f141c;border-radius:10px;padding:12px}.metric b{display:block;font-size:20px;margin-top:4px}.routes{display:grid;gap:10px}.route{display:grid;grid-template-columns:100px 170px minmax(200px,1fr) 150px minmax(230px,1fr);gap:9px;align-items:center;padding:10px;background:#0f141c;border-radius:10px}.route-health{grid-column:2/-1;font-size:12px}.credential-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}.card{background:#0f141c;border:1px solid #252e3b;border-radius:12px;padding:14px}.card-head{display:flex;justify-content:space-between;gap:12px}.badges{display:flex;gap:6px;flex-wrap:wrap;margin:10px 0}.badge{font-size:11px;padding:3px 7px;border-radius:99px;background:#252e3b}.ready,.healthy{color:#76d99e}.exhausted,.degraded{color:#ffbd69}.disabled,.unavailable,.auth-error{color:#ff8585}.actions{display:flex;gap:7px;flex-wrap:wrap;margin-top:12px}.forms{display:grid;grid-template-columns:1fr 1fr;gap:12px}.formrow{display:grid;gap:8px}input,select{width:100%;background:#0b1017;color:#edf2f8;border:1px solid #344052;border-radius:8px;padding:9px 10px}button{background:#3975e8;color:#fff;border:0;border-radius:8px;padding:9px 12px;font-weight:600;cursor:pointer}button.secondary{background:#303948}button.danger{background:#9d3640}button:disabled{opacity:.55;cursor:wait}.status{min-height:20px;margin-top:9px}.error{color:#ff9494}.success{color:#7fe0a6}.banner{padding:10px 12px;background:#493c18;border-radius:8px;margin:10px 0;display:none}.replace{margin-top:10px;padding-top:10px;border-top:1px solid #252e3b}.hidden{display:none!important}.spinner:before{content:"";display:inline-block;width:12px;height:12px;border:2px solid currentColor;border-right-color:transparent;border-radius:50%;vertical-align:-2px;margin-right:7px;animation:spin .7s linear infinite}@keyframes spin{to{transform:rotate(360deg)}}@media(max-width:900px){.overview,.credential-grid,.forms{grid-template-columns:1fr}.route{grid-template-columns:1fr}.route-health{grid-column:1}}
</style></head><body><main class="shell"><div class="top"><h1>OpenAI-CC</h1><div class="sub">Loopback control plane for Claude-compatible routing</div></div>
<section class="panel"><h2>Overview</h2><div id="overview" class="overview"></div></section>
<section class="panel"><h2>Model Routes</h2><div class="muted">Auto uses the provider's preferred ready credential first, then rotates through other ready credentials. A pin uses only that exact credential.</div><div id="external-change" class="banner">Configuration changed elsewhere. Your unsaved edits are preserved. <button id="reload-routes" class="secondary">Reload remote config</button></div><div id="routes" class="routes"></div><div class="actions"><button id="save-routes">Save model config</button></div><div id="route-status" class="status muted"></div></section>
<section class="panel"><h2>Credentials</h2><div id="credentials" class="credential-grid"></div></section>
<section class="panel"><h2>Add Credential</h2><div class="forms"><form id="oauth-form" class="card formrow"><h3>ChatGPT account</h3><input id="oauth-id" required pattern="[A-Za-z0-9._-]{1,64}" placeholder="credential id"><input id="oauth-name" required maxlength="120" placeholder="display name"><select id="oauth-mode"><option value="browser">Browser sign-in (recommended)</option><option value="device">Device sign-in fallback</option></select><button type="submit">Add ChatGPT account</button><div id="oauth-status" class="status muted"></div><button id="oauth-cancel" type="button" class="secondary hidden">Cancel sign-in</button></form>
<form id="key-form" class="card formrow"><h3>API key</h3><select id="key-provider"><option value="zen">OpenCode Zen</option><option value="nvidia">NVIDIA NIM</option><option value="google">Google AI Studio</option></select><input id="key-id" required pattern="[A-Za-z0-9._-]{1,64}" placeholder="credential id"><input id="key-name" required maxlength="120" placeholder="display name"><input id="key-model" required maxlength="256" placeholder="provider model id"><input id="key-value" type="password" required autocomplete="off" placeholder="API key"><button type="submit">Add API key</button><div id="key-status" class="status muted"></div></form></div></section>
</main><script nonce="${escapeHtml(nonce)}">window.__OPENAI_CC__=${boot};</script><script nonce="${escapeHtml(nonce)}">
(()=>{'use strict';
const boot=window.__OPENAI_CC__,slots=['default','fable','opus','sonnet','haiku'],providers=['chatgpt','zen','nvidia','google'];let state=null,modelFormDirty=false,activeJobId=null,jobTimer=null;
class ApiError extends Error{constructor(message,status,code,details){super(message);this.status=status;this.code=code;this.details=details}}
async function api(path,options={}){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),15000);try{const headers={accept:'application/json',...(options.headers||{})};if(options.body!==undefined){headers['content-type']='application/json';headers['x-openai-cc-csrf']=boot.csrfToken}const response=await fetch(path,{...options,headers,signal:controller.signal,credentials:'same-origin'});const text=await response.text();let data={};if(text){try{data=JSON.parse(text)}catch{data={error:{message:text}}}}if(!response.ok)throw new ApiError(data.error?.message||('Request failed: '+response.status),response.status,data.error?.code,data.error?.details);return data}catch(error){if(error?.name==='AbortError')throw new ApiError('Request timed out.',0,'timeout');if(error instanceof ApiError)throw error;throw new ApiError('Network request failed.',0,'network_error')}finally{clearTimeout(timer)}}
function esc(value){return String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function providerName(p){return p==='chatgpt'?'ChatGPT OAuth':p==='zen'?'OpenCode Zen':p==='nvidia'?'NVIDIA NIM':'Google AI Studio'}
function title(v){return v.charAt(0).toUpperCase()+v.slice(1)}
function setBusy(button,busy,label){if(!button)return;if(busy){button.dataset.label=button.textContent;button.textContent=label||'Working…';button.classList.add('spinner');button.disabled=true}else{button.textContent=button.dataset.label||button.textContent;button.classList.remove('spinner');button.disabled=false}}
async function refreshAll(){const next=await api('/admin/state');state=next;renderOverview();renderCredentials();if(!modelFormDirty)renderRoutes();}
async function refreshCredentialState(){const next=await api('/admin/state');state={...(state||{}),...next,modelConfig:state?.modelConfig||next.modelConfig,routeHealth:next.routeHealth};renderOverview();renderCredentials();if(!modelFormDirty)renderRoutes()}
function renderOverview(){const ready=state.accounts.filter(a=>a.status==='ready').length,exhausted=state.accounts.filter(a=>a.status==='exhausted').length,unhealthy=Object.values(state.routeHealth||{}).filter(h=>h.status==='unavailable').length;document.querySelector('#overview').innerHTML=[['Credentials',state.accounts.length],['Ready',ready],['Exhausted',exhausted],['Unavailable routes',unhealthy]].map(([k,v])=>'<div class="metric"><span class="muted">'+esc(k)+'</span><b>'+esc(v)+'</b></div>').join('')}
function renderRoutes(){const c=state.modelConfig;document.querySelector('#routes').innerHTML='<div class="route"><b>Context</b><span></span><input id="context-window" type="number" min="200000" max="1000000" value="'+c.contextWindow+'"><span></span><span class="muted">tokens</span></div>'+slots.map(slot=>routeRow(slot,c.routes[slot])).join('');document.querySelectorAll('#routes input,#routes select').forEach(el=>el.addEventListener('input',()=>{modelFormDirty=true;document.querySelector('#route-status').textContent='Unsaved changes'}));document.querySelectorAll('.route-provider').forEach(el=>el.addEventListener('change',()=>{const slot=el.dataset.slot;updatePinOptions(slot,el.value);modelFormDirty=true}));document.querySelector('#external-change').style.display='none'}
function routeRow(slot,r){const health=state.routeHealth?.[slot];return '<div class="route" data-route="'+slot+'"><b>'+title(slot)+'</b><select class="route-provider" data-slot="'+slot+'" id="p-'+slot+'">'+providers.map(p=>'<option value="'+p+'" '+(p===r.provider?'selected':'')+'>'+providerName(p)+'</option>').join('')+'</select><input id="m-'+slot+'" value="'+esc(r.model)+'" maxlength="256" placeholder="upstream model id"><input id="o-'+slot+'" type="number" min="1" max="1000000" value="'+Number(r.maxOutputTokens||64000)+'"><select id="c-'+slot+'">'+pinOptions(r.provider,r.credentialId)+'</select><div class="route-health '+esc(health?.status||'unavailable')+'">'+esc(health?.message||'')+'</div></div>'}
function pinOptions(provider,selected){const matching=state.accounts.filter(a=>a.provider===provider);return '<option value="">Auto — preferred + rotation</option>'+matching.map(a=>'<option value="'+esc(a.id)+'" '+(a.id===selected?'selected':'')+'>'+esc(a.name)+' — '+a.status.toUpperCase()+(a.limitResetsAt?' until '+new Date(a.limitResetsAt).toLocaleTimeString():'')+'</option>').join('')}
function updatePinOptions(slot,provider){const select=document.querySelector('#c-'+slot);select.innerHTML=pinOptions(provider,undefined)}
function renderCredentials(){const preferred=state.preferredCredentialByProvider||{};const used={};for(const slot of slots){const r=state.modelConfig.routes[slot];if(r.credentialId)(used[r.credentialId]??=[]).push(title(slot)+' (Pinned)');else for(const a of state.accounts.filter(a=>a.provider===r.provider))(used[a.id]??=[]).push(title(slot)+' (Auto)')}document.querySelector('#credentials').innerHTML=state.accounts.length?state.accounts.map(a=>credentialCard(a,preferred[a.provider]===a.id,used[a.id]||[])).join(''):'<div class="muted">No credentials configured.</div>';document.querySelectorAll('[data-action]').forEach(btn=>btn.addEventListener('click',()=>credentialAction(btn)));document.querySelectorAll('[data-replace-form]').forEach(form=>form.addEventListener('submit',replaceKey))}
function credentialCard(a,isPreferred,used){const reset=a.limitResetsAt?'<div class="muted countdown" data-reset="'+esc(a.limitResetsAt)+'">Ready again '+relative(a.limitResetsAt)+' · '+new Date(a.limitResetsAt).toLocaleString()+'</div>':'';const badges='<div class="badges"><span class="badge '+a.status+'">'+a.status.toUpperCase()+'</span>'+(isPreferred?'<span class="badge">PREFERRED</span>':'')+'</div>';const usage=used.length?'<div class="muted">Used by: '+used.map(esc).join(', ')+'</div>':'';const common=(a.status!=='disabled'&&!isPreferred?button('prefer',a.id,'Make preferred'):'')+(a.status==='disabled'?button('enable',a.id,'Enable'):button('disable',a.id,'Disable','secondary'))+button('delete',a.id,'Remove','danger');const specific=a.provider==='chatgpt'?button('reauth',a.id,'Re-authenticate','secondary'):button('show-replace',a.id,'Replace key','secondary');const replace=a.provider==='chatgpt'?'':'<form class="replace hidden" data-replace-form="'+esc(a.id)+'"><input name="apiKey" type="password" autocomplete="off" required placeholder="new API key"><input name="model" value="'+esc(a.model||'')+'" required placeholder="provider model id"><button type="submit">Save replacement</button><span class="status muted"></span></form>';return '<article class="card"><div class="card-head"><div><h3>'+esc(a.name)+'</h3><div class="muted">'+esc(a.id)+'</div></div><div>'+esc(providerName(a.provider))+'</div></div><div>'+esc(a.email||a.model||'')+'</div>'+badges+reset+usage+(a.lastError?'<div class="error">'+esc(a.lastError)+'</div>':'')+'<div class="actions">'+specific+common+'</div>'+replace+'</article>'}
function button(action,id,label,klass=''){return '<button type="button" class="'+klass+'" data-action="'+action+'" data-id="'+esc(id)+'">'+label+'</button>'}
async function credentialAction(buttonEl){const action=buttonEl.dataset.action,id=buttonEl.dataset.id;if(action==='show-replace'){buttonEl.closest('.card').querySelector('.replace').classList.toggle('hidden');return}if(action==='delete'&&!confirm('Remove credential '+id+'? This removes its managed authentication files.'))return;setBusy(buttonEl,true);try{let result;if(action==='prefer'||action==='disable'||action==='enable')result=await api('/admin/credentials/'+encodeURIComponent(id)+'/'+action,{method:'POST',body:'{}'});else if(action==='delete')result=await api('/admin/credentials/'+encodeURIComponent(id),{method:'DELETE',body:'{}'});else if(action==='reauth'){result=await api('/admin/credentials/'+encodeURIComponent(id)+'/reauth',{method:'POST',body:JSON.stringify({loginMode:'browser'})});activeJobId=result.jobId;watchAuth(result.jobId)}await refreshCredentialState()}catch(e){alert(e.message)}finally{setBusy(buttonEl,false)}}
async function replaceKey(event){event.preventDefault();const form=event.currentTarget,id=form.dataset.replaceForm,buttonEl=form.querySelector('button'),status=form.querySelector('.status');setBusy(buttonEl,true,'Replacing…');try{await api('/admin/credentials/'+encodeURIComponent(id)+'/replace-key',{method:'POST',body:JSON.stringify({apiKey:form.apiKey.value,model:form.model.value})});form.apiKey.value='';status.textContent='Replaced.';status.className='status success';await refreshCredentialState()}catch(e){status.textContent=e.message;status.className='status error'}finally{setBusy(buttonEl,false)}}
async function saveRoutes(){const buttonEl=document.querySelector('#save-routes'),status=document.querySelector('#route-status');setBusy(buttonEl,true,'Saving…');try{const routes={};for(const slot of slots)routes[slot]={provider:document.querySelector('#p-'+slot).value,model:document.querySelector('#m-'+slot).value.trim(),maxOutputTokens:Number(document.querySelector('#o-'+slot).value),credentialId:document.querySelector('#c-'+slot).value||undefined};await api('/admin/model-config',{method:'POST',body:JSON.stringify({contextWindow:Number(document.querySelector('#context-window').value),routes})});modelFormDirty=false;status.textContent='Saved. Gateway routing and /v1/models are updated immediately.';status.className='status success';await refreshAll()}catch(e){status.textContent=e.message;status.className='status error'}finally{setBusy(buttonEl,false)}}
async function startOAuth(event){event.preventDefault();const form=event.currentTarget,buttonEl=form.querySelector('button[type=submit]'),status=document.querySelector('#oauth-status');setBusy(buttonEl,true,'Starting login…');try{const result=await api('/admin/chatgpt/auth',{method:'POST',body:JSON.stringify({id:form.querySelector('#oauth-id').value.trim(),name:form.querySelector('#oauth-name').value.trim(),loginMode:form.querySelector('#oauth-mode').value})});activeJobId=result.jobId;status.textContent=result.safeMessage||'Login started.';document.querySelector('#oauth-cancel').classList.remove('hidden');watchAuth(result.jobId)}catch(e){status.textContent=e.message;status.className='status error';setBusy(buttonEl,false)}}
async function watchAuth(jobId){clearTimeout(jobTimer);const status=document.querySelector('#oauth-status'),buttonEl=document.querySelector('#oauth-form button[type=submit]'),cancel=document.querySelector('#oauth-cancel');try{const job=await api('/admin/auth-jobs/'+encodeURIComponent(jobId));status.textContent=job.safeError?((job.safeMessage||'Authentication failed')+' '+job.safeError):(job.safeMessage||job.status);status.className='status '+(job.status==='complete'?'success':job.status==='error'?'error':'muted');if(['complete','error','cancelled'].includes(job.status)){activeJobId=null;cancel.classList.add('hidden');setBusy(buttonEl,false);if(job.status==='complete'){document.querySelector('#oauth-id').value='';document.querySelector('#oauth-name').value='';await refreshCredentialState()}return}jobTimer=setTimeout(()=>watchAuth(jobId),900)}catch(e){status.textContent=e.message;status.className='status error';setBusy(buttonEl,false)}}
async function cancelOAuth(){if(!activeJobId)return;const buttonEl=document.querySelector('#oauth-cancel');setBusy(buttonEl,true,'Cancelling…');try{await api('/admin/auth-jobs/'+encodeURIComponent(activeJobId)+'/cancel',{method:'POST',body:'{}'});await watchAuth(activeJobId)}catch(e){document.querySelector('#oauth-status').textContent=e.message}finally{setBusy(buttonEl,false)}}
async function addKey(event){event.preventDefault();const form=event.currentTarget,buttonEl=form.querySelector('button'),status=document.querySelector('#key-status');setBusy(buttonEl,true,'Adding…');try{await api('/admin/credentials',{method:'POST',body:JSON.stringify({provider:document.querySelector('#key-provider').value,id:document.querySelector('#key-id').value.trim(),name:document.querySelector('#key-name').value.trim(),model:document.querySelector('#key-model').value.trim(),apiKey:document.querySelector('#key-value').value})});document.querySelector('#key-value').value='';status.textContent='Credential added.';status.className='status success';await refreshCredentialState()}catch(e){status.textContent=e.message;status.className='status error'}finally{setBusy(buttonEl,false)}}
function relative(value){const ms=Date.parse(value)-Date.now();if(ms<=0)return'now';const m=Math.ceil(ms/60000),h=Math.floor(m/60);return h?('in '+h+'h '+(m%60)+'m'):('in '+m+'m')}
setInterval(()=>document.querySelectorAll('.countdown').forEach(el=>{const value=el.dataset.reset;el.textContent='Ready again '+relative(value)+' · '+new Date(value).toLocaleString()}),30000);
document.querySelector('#save-routes').addEventListener('click',saveRoutes);document.querySelector('#oauth-form').addEventListener('submit',startOAuth);document.querySelector('#key-form').addEventListener('submit',addKey);document.querySelector('#oauth-cancel').addEventListener('click',cancelOAuth);document.querySelector('#reload-routes').addEventListener('click',()=>{modelFormDirty=false;renderRoutes()});
const events=new EventSource('/admin/events');['credentials_changed','credential_status_changed','preferred_changed','auth_job_changed'].forEach(type=>events.addEventListener(type,()=>refreshCredentialState().catch(()=>{})));events.addEventListener('model_config_changed',async()=>{const next=await api('/admin/state').catch(()=>null);if(!next)return;state=next;renderOverview();renderCredentials();if(modelFormDirty)document.querySelector('#external-change').style.display='block';else renderRoutes()});events.addEventListener('state',event=>{try{const next=JSON.parse(event.data);state=next;renderOverview();renderCredentials();if(!modelFormDirty)renderRoutes()}catch{}});refreshAll().catch(e=>{document.querySelector('#route-status').textContent=e.message;document.querySelector('#route-status').className='status error'});
})();
</script></body></html>`;
}

function escapeHtml(value: string): string {
  return String(value).replace(/[&<>"']/g, (char) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[char] ?? char));
}
