export function adminPage(csrfToken: string, nonce: string): string {
  const boot = JSON.stringify({ csrfToken }).replace(/</g, "\\u003c");
  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>OpenAI-CC Admin</title>
<style nonce="${escapeHtml(nonce)}">
:root{color-scheme:dark;font-family:Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;--bg:#0d0d0d;--surface:#171717;--raised:#212121;--raised-2:#272727;--border:#303030;--text:#ececec;--muted:#a7a7a7;--faint:#777;--accent:#7dd3a8;--warn:#e7b970;--danger:#ef8d8d}
*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--text);font-size:14px;line-height:1.45}.shell{width:min(1120px,calc(100% - 32px));margin:0 auto;padding:28px 0 64px}.header{text-align:center;padding:8px 0 22px}.brand{display:inline-flex;align-items:center;justify-content:center;gap:10px}.claude-mark{width:25px;height:25px;display:inline-grid;place-items:center;color:#d9d9d9}.claude-mark svg{width:100%;height:100%;display:block}.header h1{font-size:24px;line-height:1.1;letter-spacing:-.02em;margin:0;font-weight:650}.header p{margin:8px 0 0;color:var(--muted);font-size:13px}
.surface{background:var(--surface);border:1px solid var(--border);border-radius:14px;margin:12px 0;padding:18px}.section-head{display:flex;align-items:center;justify-content:space-between;gap:12px;margin-bottom:14px}.section-head h2{font-size:16px;margin:0;font-weight:650;letter-spacing:-.01em}.section-note{color:var(--muted);font-size:12px;margin:-6px 0 14px}
.system-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:1px;background:var(--border);border:1px solid var(--border);border-radius:10px;overflow:hidden}.system-item{background:var(--raised);padding:11px 12px;min-width:0}.system-item span{display:block;color:var(--muted);font-size:11px;margin-bottom:3px}.system-item strong{font-size:13px;font-weight:600;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}
.status-pill{display:inline-flex;align-items:center;gap:6px;border:1px solid var(--border);background:var(--raised);border-radius:999px;padding:4px 8px;font-size:11px;color:var(--muted);white-space:nowrap}.status-pill:before{content:"";width:6px;height:6px;border-radius:50%;background:currentColor}.ready,.healthy,.connected{color:var(--accent)}.exhausted,.degraded,.pending{color:var(--warn)}.disabled,.unavailable,.auth-error,.error-state{color:var(--danger)}
.routes-list{display:grid;gap:9px}.route-card{background:var(--raised);border:1px solid var(--border);border-radius:11px;padding:13px}.route-top{display:flex;align-items:flex-start;justify-content:space-between;gap:12px;margin-bottom:11px}.route-name{display:flex;align-items:baseline;gap:9px}.route-name h3{font-size:15px;margin:0;font-weight:650}.route-name span{font-size:11px;color:var(--muted)}.route-fields{display:grid;grid-template-columns:1.05fr 1.65fr 1.35fr .8fr .8fr;gap:9px}.route-capabilities{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:9px;margin-top:9px}.field{display:grid;gap:5px;min-width:0}.field label{font-size:10px;text-transform:uppercase;letter-spacing:.07em;color:var(--faint);font-weight:650}.field input,.field select{width:100%;min-width:0;background:var(--bg);color:var(--text);border:1px solid #3a3a3a;border-radius:8px;padding:8px 9px;font:inherit;outline:none}.field input:focus,.field select:focus{border-color:#626262}.route-facts{display:flex;flex-wrap:wrap;gap:8px 16px;margin-top:10px;color:var(--muted);font-size:11px}.route-facts strong{color:var(--text);font-weight:550}.route-health{margin-top:7px;font-size:11px}.route-settings{display:flex;align-items:end;justify-content:flex-end;gap:14px;border-top:1px solid var(--border);margin-top:13px;padding-top:13px}.secondary-route{margin-top:9px;border:1px solid var(--border);border-radius:10px;background:#191919}.secondary-route summary{cursor:pointer;padding:10px 12px;color:var(--muted);font-size:12px;user-select:none}.secondary-route[open] summary{border-bottom:1px solid var(--border)}.secondary-route .route-card{border:0;border-radius:0;background:transparent}
.banner{display:none;margin:0 0 12px;padding:9px 11px;border:1px solid #5c4b30;background:#2a241a;border-radius:9px;color:#e8d5b5;font-size:12px}.credentials{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:9px}.credential{background:var(--raised);border:1px solid var(--border);border-radius:11px;padding:13px;min-width:0}.credential-head{display:flex;justify-content:space-between;gap:12px;align-items:flex-start}.credential-title{min-width:0}.credential-title h3{margin:0;font-size:14px;font-weight:650;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.credential-title p{margin:3px 0 0;color:var(--muted);font-size:11px}.credential-meta{display:flex;flex-wrap:wrap;gap:6px;margin-top:10px}.credential-line{margin-top:8px;color:var(--muted);font-size:11px;overflow-wrap:anywhere}.credential-error{margin-top:8px;color:var(--danger);font-size:11px;overflow-wrap:anywhere}.actions{display:flex;flex-wrap:wrap;gap:7px;margin-top:11px}
button{appearance:none;border:1px solid #454545;background:#efefef;color:#111;border-radius:8px;padding:8px 10px;font:inherit;font-weight:600;cursor:pointer}button:hover{background:#fff}button.secondary{background:var(--raised-2);color:var(--text);border-color:#444}button.secondary:hover{background:#303030}button.danger{background:transparent;color:#e7a0a0;border-color:#5a3838}button.danger:hover{background:#2b1b1b}button.small{padding:6px 8px;font-size:11px}button:disabled{opacity:.55;cursor:wait}
.add-grid{display:grid;grid-template-columns:1fr 1fr;gap:9px;margin-top:14px;padding-top:14px;border-top:1px solid var(--border)}.form-card{background:var(--raised);border:1px solid var(--border);border-radius:11px;padding:13px}.form-card h3{font-size:13px;margin:0 0 10px}.form-stack{display:grid;gap:8px}.form-stack .helper,.helper{color:var(--muted);font-size:11px}.status{min-height:18px;margin-top:7px;font-size:11px;color:var(--muted)}.success{color:var(--accent)}.error{color:var(--danger)}.replace{margin-top:10px;padding-top:10px;border-top:1px solid var(--border)}.hidden{display:none!important}
.catalogs{display:grid;gap:9px}.catalog{background:var(--raised);border:1px solid var(--border);border-radius:11px;overflow:hidden}.catalog-head{display:flex;align-items:center;justify-content:space-between;gap:12px;padding:11px 12px;border-bottom:1px solid var(--border)}.catalog-head h3{margin:0;font-size:13px}.catalog-head p{margin:2px 0 0;color:var(--muted);font-size:11px}.model-list{max-height:360px;overflow:auto}.model-row{display:grid;grid-template-columns:minmax(220px,1.5fr) minmax(130px,.7fr) minmax(140px,.85fr);gap:10px;padding:9px 12px;border-top:1px solid #2b2b2b;align-items:center}.model-row:first-child{border-top:0}.model-name{font-size:12px;font-weight:600;min-width:0}.model-id{display:block;color:var(--muted);font-size:10px;font-weight:400;margin-top:2px;overflow-wrap:anywhere}.model-spec{color:var(--muted);font-size:10px}.model-cap{display:flex;flex-wrap:wrap;gap:5px;justify-content:flex-end}.cap{border:1px solid #414141;border-radius:999px;padding:2px 6px;font-size:9px;color:#bdbdbd}.catalog-message{padding:14px 12px;color:var(--muted);font-size:11px}.catalog-message.error{color:var(--danger)}.spinner:before{content:"";display:inline-block;width:11px;height:11px;border:2px solid currentColor;border-right-color:transparent;border-radius:50%;vertical-align:-2px;margin-right:6px;animation:spin .7s linear infinite}@keyframes spin{to{transform:rotate(360deg)}}a{color:#b8c7ff}.device-box{display:grid;gap:6px;margin-top:4px;padding:9px;background:var(--bg);border:1px solid var(--border);border-radius:8px;font-size:11px}code{font-size:14px;font-weight:700;letter-spacing:.08em}.empty{color:var(--muted);font-size:12px;padding:4px 0}.sr-only{position:absolute;width:1px;height:1px;padding:0;margin:-1px;overflow:hidden;clip:rect(0,0,0,0);white-space:nowrap;border:0}
@media(max-width:900px){.system-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.route-fields{grid-template-columns:1fr 1fr}.route-capabilities{grid-template-columns:repeat(3,minmax(0,1fr))}.credentials,.add-grid{grid-template-columns:1fr}.model-row{grid-template-columns:1fr 1fr}.model-cap{grid-column:1/-1;justify-content:flex-start}}
@media(max-width:620px){.shell{width:min(100% - 20px,1120px);padding-top:18px}.surface{padding:14px;border-radius:12px}.system-grid,.route-fields,.route-capabilities,.model-row{grid-template-columns:1fr}.route-settings{align-items:stretch;flex-direction:column}.route-settings button{width:100%}.section-head{align-items:flex-start}.credential-head{flex-direction:column}.model-cap{grid-column:auto}.header{padding-bottom:16px}}
</style>
</head>
<body><main class="shell">
<header class="header"><div class="brand"><span class="claude-mark" aria-label="Claude"><svg viewBox="0 0 24 24" role="img" aria-hidden="true"><g fill="currentColor"><rect x="10.8" y="1.5" width="2.4" height="8" rx="1.2"/><rect x="10.8" y="14.5" width="2.4" height="8" rx="1.2"/><rect x="1.5" y="10.8" width="8" height="2.4" rx="1.2"/><rect x="14.5" y="10.8" width="8" height="2.4" rx="1.2"/><rect x="4.35" y="4.35" width="2.4" height="8" rx="1.2" transform="rotate(-45 5.55 8.35)"/><rect x="17.25" y="11.65" width="2.4" height="8" rx="1.2" transform="rotate(-45 18.45 15.65)"/><rect x="11.65" y="4.35" width="8" height="2.4" rx="1.2" transform="rotate(-45 15.65 5.55)"/><rect x="4.35" y="17.25" width="8" height="2.4" rx="1.2" transform="rotate(-45 8.35 18.45)"/></g></svg></span><h1>OpenAI-CC</h1></div><p>Claude routing control plane</p></header>
<section class="surface"><div class="section-head"><h2>System</h2><span id="gateway-status" class="status-pill pending">Connecting</span></div><div id="system-status" class="system-grid"></div></section>
<section class="surface">
  <div class="section-head"><h2>Routes</h2><span class="section-note">Actual upstream configuration</span></div>
  <div class="section-note">Models are discovered from configured credentials. Context window, vision, tools, and reasoning are model-specific and editable on each route. Selecting a discovered model seeds its reported context when available.</div>
  <div id="external-change" class="banner">Configuration changed elsewhere. Your unsaved edits are preserved. <button id="reload-routes" type="button" class="secondary small">Reload remote config</button></div>
  <div id="routes-primary" class="routes-list"></div>
  <details class="secondary-route"><summary>Default route (Claude Code fallback)</summary><div id="route-default"></div></details>
  <div class="route-settings"><div><button id="save-routes" type="button">Save routing</button><div id="route-status" class="status"></div></div></div>
</section>
<section class="surface"><div class="section-head"><h2>Credentials</h2><span id="credential-summary" class="section-note"></span></div><div id="credentials" class="credentials"></div><div class="add-grid"><form id="oauth-form" class="form-card"><h3>Add ChatGPT account</h3><div class="form-stack"><div class="helper">Sign in with OAuth. The account email becomes the visible identity; no credential name or storage path is required.</div><div class="field"><label for="oauth-mode">Sign-in method</label><select id="oauth-mode"><option value="browser">Browser sign-in</option><option value="device">Device-code fallback</option></select></div><button type="submit">Add ChatGPT account</button><div id="oauth-device" class="device-box hidden"><a id="oauth-device-link" href="#" target="_blank" rel="noreferrer noopener">Open official sign-in</a><div>One-time code: <code id="oauth-device-code"></code></div></div><div id="oauth-status" class="status"></div><button id="oauth-cancel" type="button" class="secondary hidden">Cancel sign-in</button></div></form><form id="key-form" class="form-card"><h3>Add API-key credential</h3><div class="form-stack"><div class="field"><label for="key-provider">Provider</label><select id="key-provider"></select></div><div class="field"><label for="key-value">API key</label><input id="key-value" type="password" required autocomplete="off" placeholder="Paste API key"></div><div class="field"><label for="key-name">Display name <span class="sr-only">optional</span></label><input id="key-name" maxlength="120" autocomplete="off" placeholder="Optional"></div><div id="key-account-wrap" class="field"><label for="key-account">Cloudflare Account ID</label><input id="key-account" maxlength="128" autocomplete="off" placeholder="Required for Cloudflare"></div><div class="helper">Internal credential IDs are generated automatically. Models are discovered after the credential is added.</div><button type="submit">Add credential</button><div id="key-status" class="status"></div></div></form></div></section>
<section class="surface" id="custom-providers-section"><div class="section-head"><h2>Custom providers</h2><span class="section-note">OpenAI-compatible endpoints</span></div><div class="section-note">Define the endpoint once, then add an API-key credential. Model IDs are discovered automatically from the provider API; there is no manual model catalog.</div><div id="custom-providers" class="credentials"></div><form id="provider-form" class="form-card" style="margin-top:14px"><h3>Add custom provider</h3><div class="route-fields"><div class="field"><label for="provider-name">Display name</label><input id="provider-name" maxlength="120" required placeholder="My provider"></div><div class="field"><label for="provider-url">Base URL</label><input id="provider-url" required placeholder="https://example.com/v1"></div><div class="field"><label for="provider-style">API style</label><select id="provider-style"><option value="chat-completions">Chat Completions</option><option value="responses">Responses</option></select></div><div class="field"><label for="provider-tier">Service tier <span class="sr-only">optional</span></label><input id="provider-tier" maxlength="64" placeholder="Optional, e.g. flex"></div><div class="field"><button type="submit">Add provider</button></div></div><div id="provider-status" class="status"></div></form></section>
<section id="models-section" class="surface"><div class="section-head"><h2>Available models</h2><button id="refresh-models" type="button" class="secondary small">Refresh catalogs</button></div><div class="section-note">Catalogs come directly from each configured credential/provider. Discovered context and capability metadata can seed route settings, while the saved route values remain editable in Routes above.</div><div id="model-catalogs" class="catalogs"></div></section>
</main>
<script nonce="${escapeHtml(nonce)}">window.__OPENAI_CC__=${boot};</script>
<script nonce="${escapeHtml(nonce)}">
(()=>{'use strict';
const boot=window.__OPENAI_CC__,primarySlots=['fable','opus','sonnet','haiku'],slots=['default',...primarySlots];
let state=null,modelFormDirty=false,activeJobId=null,jobTimer=null;
const discovered=new Map(),discoveryErrors=new Map(),discoveryLoading=new Set();
class ApiError extends Error{constructor(message,status,code,details){super(message);this.status=status;this.code=code;this.details=details}}
async function api(path,options={}){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),15000);try{const headers={accept:'application/json',...(options.headers||{})};if(options.body!==undefined){headers['content-type']='application/json';headers['x-openai-cc-csrf']=boot.csrfToken}const response=await fetch(path,{...options,headers,signal:controller.signal,credentials:'same-origin'});const text=await response.text();let data={};if(text){try{data=JSON.parse(text)}catch{data={error:{message:text}}}}if(!response.ok)throw new ApiError(data.error?.message||('Request failed: '+response.status),response.status,data.error?.code,data.error?.details);return data}catch(error){if(error?.name==='AbortError')throw new ApiError('Request timed out.',0,'timeout');if(error instanceof ApiError)throw error;throw new ApiError('Network request failed.',0,'network_error')}finally{clearTimeout(timer)}}
function esc(value){return String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function providerMeta(id){return (state?.providers||[]).find(p=>p.id===id)}
function providerName(id){return providerMeta(id)?.displayName||id}
function providerIds(){return (state?.providers||[]).map(p=>p.id)}
function title(v){return v.charAt(0).toUpperCase()+v.slice(1)}
function statusLabel(v){return String(v||'unknown').replace(/_/g,' ')}
function statusClass(v){return String(v||'unavailable').replace(/_/g,'-')}
function identity(a){return a.email||a.name||providerName(a.provider)}
function setBusy(button,busy,label){if(!button)return;if(busy){if(!button.dataset.label)button.dataset.label=button.textContent;button.textContent=label||'Working…';button.classList.add('spinner');button.disabled=true}else{button.textContent=button.dataset.label||button.textContent;button.classList.remove('spinner');button.disabled=false;delete button.dataset.label}}
function pruneDiscovery(){const ids=new Set((state?.accounts||[]).map(a=>a.id));for(const id of discovered.keys())if(!ids.has(id))discovered.delete(id);for(const id of discoveryErrors.keys())if(!ids.has(id))discoveryErrors.delete(id)}
async function refreshAll(){const next=await api('/admin/state');state=next;pruneDiscovery();renderAll();discoverAll(false)}
async function refreshCredentialState(){const next=await api('/admin/state');state={...(state||{}),...next,modelConfig:state?.modelConfig||next.modelConfig,routeHealth:next.routeHealth};pruneDiscovery();renderSystem();renderProviderControls();renderCredentials();renderCustomProviders();renderCatalogs();if(!modelFormDirty)renderRoutes();discoverAll(false)}
function renderAll(){renderSystem();renderProviderControls();renderRoutes();renderCredentials();renderCustomProviders();renderCatalogs();document.querySelector('#gateway-status').textContent='Connected';document.querySelector('#gateway-status').className='status-pill connected'}
function contextSummary(){const values=slots.map(slot=>Number(state.modelConfig.routes[slot]?.contextWindow||0)).filter(Boolean);if(!values.length)return'Not configured';const min=Math.min(...values),max=Math.max(...values);return min===max?Number(min).toLocaleString()+' tokens':Number(min).toLocaleString()+'–'+Number(max).toLocaleString()+' tokens'}
function renderSystem(){if(!state)return;const health=Object.values(state.routeHealth||{}),healthy=health.filter(h=>h.status==='healthy').length,ready=state.accounts.filter(a=>a.status==='ready').length,providerCount=new Set(state.accounts.map(a=>a.provider)).size;document.querySelector('#system-status').innerHTML=[['Route health',healthy+'/'+health.length+' healthy'],['Credentials',ready+'/'+state.accounts.length+' ready'],['Providers',providerCount+' configured'],['Context windows',contextSummary()]].map(([k,v])=>'<div class="system-item"><span>'+esc(k)+'</span><strong>'+esc(v)+'</strong></div>').join('');document.querySelector('#credential-summary').textContent=ready+' ready · '+state.accounts.length+' total'}
function renderRoutes(){if(!state)return;document.querySelector('#routes-primary').innerHTML=primarySlots.map(slot=>routeCard(slot,state.modelConfig.routes[slot])).join('');document.querySelector('#route-default').innerHTML=routeCard('default',state.modelConfig.routes.default);bindRouteControls();document.querySelector('#external-change').style.display='none'}
function routeCard(slot,r){const health=state.routeHealth?.[slot],status=health?.status||'unavailable';return '<article class="route-card" data-route="'+slot+'"><div class="route-top"><div class="route-name"><h3>'+title(slot)+'</h3><span>'+esc(r.model)+'</span></div><span class="status-pill '+statusClass(status)+'" data-route-status="'+slot+'">'+esc(statusLabel(status))+'</span></div><div class="route-fields"><div class="field"><label for="p-'+slot+'">Provider</label><select class="route-provider" data-slot="'+slot+'" id="p-'+slot+'">'+providerOptions(r.provider)+'</select></div><div class="field"><label for="m-'+slot+'">Model</label><select class="route-model" data-slot="'+slot+'" id="m-'+slot+'">'+modelOptions(r.provider,r.model)+'</select></div><div class="field"><label for="c-'+slot+'">Credential</label><select id="c-'+slot+'">'+pinOptions(r.provider,r.credentialId)+'</select></div><div class="field"><label for="ctx-'+slot+'">Context window</label><input class="route-context" data-slot="'+slot+'" id="ctx-'+slot+'" type="number" min="1" max="1000000" inputmode="numeric" value="'+Number(r.contextWindow||200000)+'"></div><div class="field"><label for="o-'+slot+'">Max output</label><input id="o-'+slot+'" type="number" min="1" max="1000000" inputmode="numeric" value="'+Number(r.maxOutputTokens||16384)+'"></div></div><div class="route-capabilities">'+capabilityField(slot,'vision','Vision',r.vision,r.provider,r.model)+capabilityField(slot,'tools','Tools',r.tools,r.provider,r.model)+capabilityField(slot,'reasoning','Reasoning',r.reasoning,r.provider,r.model)+'</div><div class="route-facts" data-route-facts="'+slot+'">'+routeFacts(slot,r.provider,r.model,true)+'</div><div class="route-health '+statusClass(status)+'" data-route-health="'+slot+'">'+esc(health?.message||'Route health unavailable.')+'</div></article>'}
function providerOptions(selected){return providerIds().map(p=>'<option value="'+esc(p)+'" '+(p===selected?'selected':'')+'>'+esc(providerName(p))+'</option>').join('')}
function providerModels(provider){const byId=new Map();for(const a of state.accounts.filter(a=>a.provider===provider)){for(const m of discovered.get(a.id)||[]){if(!byId.has(m.upstreamModelId))byId.set(m.upstreamModelId,m)}}return [...byId.values()].sort((a,b)=>String(a.friendlyName||a.upstreamModelId).localeCompare(String(b.friendlyName||b.upstreamModelId)))}
function configuredModels(provider){const values=[];for(const slot of slots){const r=state.modelConfig.routes[slot];if(r.provider===provider&&!values.includes(r.model))values.push(r.model)}return values}
function modelOptions(provider,selected){const models=providerModels(provider),seen=new Set(models.map(m=>m.upstreamModelId)),configured=configuredModels(provider);let html='';if(selected&&!seen.has(selected))html+='<option value="'+esc(selected)+'" selected>'+esc(selected)+' — configured</option>';for(const id of configured){if(id!==selected&&!seen.has(id))html+='<option value="'+esc(id)+'">'+esc(id)+' — configured</option>'}html+=models.map(m=>'<option value="'+esc(m.upstreamModelId)+'" '+(m.upstreamModelId===selected?'selected':'')+'>'+esc((m.friendlyName?m.friendlyName+' — ':'')+m.upstreamModelId)+'</option>').join('');return html||'<option value="">No discovered models</option>'}
function pinOptions(provider,selected){const matching=state.accounts.filter(a=>a.provider===provider);return '<option value="">Auto — preferred + rotation</option>'+matching.map(a=>'<option value="'+esc(a.id)+'" '+(a.id===selected?'selected':'')+'>'+esc(identity(a))+' — '+esc(statusLabel(a.status))+'</option>').join('')}
function findModel(provider,model){return providerModels(provider).find(m=>m.upstreamModelId===model)}
function detectedCapability(provider,model,key){const meta=findModel(provider,model),caps=meta?.capabilities;if(!caps)return undefined;return key==='vision'?caps.image:caps[key]}
function capabilityField(slot,key,label,value,provider,model){const detected=detectedCapability(provider,model,key),autoLabel=detected===undefined?'Auto — not reported':('Auto — '+(detected?'supported':'not supported'));return '<div class="field"><label for="cap-'+key+'-'+slot+'">'+label+'</label><select class="route-capability" data-slot="'+slot+'" data-capability="'+key+'" id="cap-'+key+'-'+slot+'"><option value="" '+(value===undefined?'selected':'')+'>'+autoLabel+'</option><option value="true" '+(value===true?'selected':'')+'>Supported</option><option value="false" '+(value===false?'selected':'')+'>Not supported</option></select></div>'}
function routeFacts(slot,provider,model,saved){const meta=findModel(provider,model),health=state.routeHealth?.[slot],sameSaved=saved&&health?.provider===provider&&health?.model===model,configured=Number(document.querySelector('#ctx-'+slot)?.value||state.modelConfig.routes[slot]?.contextWindow||0),reported=meta?.contextWindow,effective=sameSaved?health?.contextWindow:configured;return '<span>Configured context: <strong>'+(configured?Number(configured).toLocaleString()+' tokens':'Not set')+'</strong></span><span>API reported: <strong>'+(reported?Number(reported).toLocaleString()+' tokens':'Not reported')+'</strong></span><span>Gateway context: <strong>'+(effective?Number(effective).toLocaleString()+' tokens':'Pending save')+'</strong></span>'}
function bindRouteControls(){document.querySelectorAll('#routes-primary input,#routes-primary select,#route-default input,#route-default select').forEach(el=>el.addEventListener('input',markRoutesDirty));document.querySelectorAll('.route-provider').forEach(el=>el.addEventListener('change',()=>changeRouteProvider(el.dataset.slot,el.value)));document.querySelectorAll('.route-model').forEach(el=>el.addEventListener('change',()=>changeRouteModel(el.dataset.slot,el.value)));document.querySelectorAll('.route-context').forEach(el=>el.addEventListener('input',()=>renderPendingFacts(el.dataset.slot)))}
function markRoutesDirty(){modelFormDirty=true;const status=document.querySelector('#route-status');status.textContent='Unsaved changes';status.className='status'}
function resetCapabilityOverrides(slot){for(const key of ['vision','tools','reasoning']){const el=document.querySelector('#cap-'+key+'-'+slot);if(el)el.value=''}}
function refreshCapabilityLabels(slot){const provider=document.querySelector('#p-'+slot)?.value,model=document.querySelector('#m-'+slot)?.value;for(const key of ['vision','tools','reasoning']){const el=document.querySelector('#cap-'+key+'-'+slot);if(!el)continue;const option=el.options[0],detected=detectedCapability(provider,model,key);option.textContent=detected===undefined?'Auto — not reported':('Auto — '+(detected?'supported':'not supported'))}}
function seedDiscoveredLimits(slot,provider,modelId,replaceContext){const meta=findModel(provider,modelId),ctx=document.querySelector('#ctx-'+slot),out=document.querySelector('#o-'+slot);if(meta?.contextWindow&&ctx&&(replaceContext||!Number(ctx.value)))ctx.value=String(meta.contextWindow);if(meta?.maxOutputTokens&&out&&Number(out.value)>meta.maxOutputTokens)out.value=String(meta.maxOutputTokens)}
async function changeRouteProvider(slot,provider){markRoutesDirty();const credential=document.querySelector('#c-'+slot),model=document.querySelector('#m-'+slot);credential.innerHTML=pinOptions(provider,undefined);model.innerHTML='<option value="">Loading discovered models…</option>';model.disabled=true;resetCapabilityOverrides(slot);renderPendingFacts(slot);await ensureProviderModels(provider,false);const models=providerModels(provider),fallback=configuredModels(provider),selected=models[0]?.upstreamModelId||fallback[0]||'';model.innerHTML=modelOptions(provider,selected);model.disabled=false;seedDiscoveredLimits(slot,provider,selected,true);refreshCapabilityLabels(slot);renderPendingFacts(slot)}
function changeRouteModel(slot,modelId){const provider=document.querySelector('#p-'+slot).value;seedDiscoveredLimits(slot,provider,modelId,true);resetCapabilityOverrides(slot);refreshCapabilityLabels(slot);markRoutesDirty();renderPendingFacts(slot)}
function renderPendingFacts(slot){const card=document.querySelector('[data-route="'+slot+'"]');if(!card)return;const provider=document.querySelector('#p-'+slot)?.value,model=document.querySelector('#m-'+slot)?.value,facts=card.querySelector('[data-route-facts]'),health=card.querySelector('[data-route-health]'),pill=card.querySelector('[data-route-status]');if(facts)facts.innerHTML=routeFacts(slot,provider,model,false);if(modelFormDirty&&health){health.textContent='Pending save — route health will refresh after the configuration is applied.';health.className='route-health pending'}if(modelFormDirty&&pill){pill.textContent='pending';pill.className='status-pill pending'}}
function readCapability(slot,key){const value=document.querySelector('#cap-'+key+'-'+slot)?.value;return value===''?null:value==='true'}
function renderCredentials(){if(!state)return;const preferred=state.preferredCredentialByProvider||{},used={};for(const slot of slots){const r=state.modelConfig.routes[slot];if(r.credentialId)(used[r.credentialId]??=[]).push(title(slot)+' (pinned)');else for(const a of state.accounts.filter(a=>a.provider===r.provider))(used[a.id]??=[]).push(title(slot)+' (auto)')}document.querySelector('#credentials').innerHTML=state.accounts.length?state.accounts.map(a=>credentialCard(a,preferred[a.provider]===a.id,used[a.id]||[])).join(''):'<div class="empty">No credentials configured.</div>';document.querySelectorAll('[data-action]').forEach(btn=>btn.addEventListener('click',()=>credentialAction(btn)));document.querySelectorAll('[data-replace-form]').forEach(form=>form.addEventListener('submit',replaceKey))}
function credentialCard(a,isPreferred,used){const reset=a.limitResetsAt?'<div class="credential-line countdown" data-reset="'+esc(a.limitResetsAt)+'">Ready again '+relative(a.limitResetsAt)+'</div>':'',badges='<div class="credential-meta"><span class="status-pill '+statusClass(a.status)+'">'+esc(statusLabel(a.status))+'</span>'+(isPreferred?'<span class="status-pill">preferred</span>':'')+'</div>',usage=used.length?'<div class="credential-line">Routes: '+used.map(esc).join(', ')+'</div>':'',account=a.accountId?'<div class="credential-line">Account ID: '+esc(a.accountId)+'</div>':'',display=a.email&&a.name&&a.name!==a.email&&a.name!=='ChatGPT account'?'<div class="credential-line">Display name: '+esc(a.name)+'</div>':'',common=(a.status==='ready'&&!isPreferred?button('prefer',a.id,'Make preferred'):'')+(a.status==='disabled'?button('enable',a.id,'Enable'):button('disable',a.id,'Disable','secondary'))+button('models',a.id,'Models','secondary')+button('delete',a.id,'Remove','danger'),specific=a.provider==='chatgpt'?button('reauth',a.id,'Re-authenticate','secondary'):button('show-replace',a.id,'Replace key','secondary'),replace=a.provider==='chatgpt'?'':'<form class="replace hidden form-stack" data-replace-form="'+esc(a.id)+'"><div class="field"><label>New API key</label><input name="apiKey" type="password" autocomplete="off" required placeholder="Paste replacement key"></div>'+(a.provider==='cloudflare'?'<div class="field"><label>Cloudflare Account ID</label><input name="accountId" value="'+esc(a.accountId||'')+'" required></div>':'')+'<button type="submit">Save replacement</button><span class="status"></span></form>';return '<article class="credential"><div class="credential-head"><div class="credential-title"><h3>'+esc(identity(a))+'</h3><p>'+esc(providerName(a.provider))+'</p></div></div>'+display+account+badges+reset+usage+(a.lastError?'<div class="credential-error">'+esc(a.lastError)+'</div>':'')+'<div class="actions">'+specific+common+'</div>'+replace+'</article>'}
function button(action,id,label,klass=''){return '<button type="button" class="small '+klass+'" data-action="'+action+'" data-id="'+esc(id)+'">'+label+'</button>'}
async function credentialAction(buttonEl){const action=buttonEl.dataset.action,id=buttonEl.dataset.id,account=state.accounts.find(a=>a.id===id);if(action==='show-replace'){buttonEl.closest('.credential').querySelector('.replace').classList.toggle('hidden');return}if(action==='models'){document.querySelector('#models-section').scrollIntoView({behavior:'smooth',block:'start'});const card=document.querySelector('[data-catalog-id="'+CSS.escape(id)+'"]');if(card)card.scrollIntoView({behavior:'smooth',block:'center'});return}if(action==='delete'&&!confirm('Remove '+identity(account)+'?'))return;setBusy(buttonEl,true);try{let result;if(action==='prefer'||action==='disable'||action==='enable')result=await api('/admin/credentials/'+encodeURIComponent(id)+'/'+action,{method:'POST',body:'{}'});else if(action==='delete')result=await api('/admin/credentials/'+encodeURIComponent(id),{method:'DELETE',body:'{}'});else if(action==='reauth'){result=await api('/admin/credentials/'+encodeURIComponent(id)+'/reauth',{method:'POST',body:JSON.stringify({loginMode:'browser'})});activeJobId=result.jobId;watchAuth(result.jobId)}await refreshCredentialState()}catch(e){alert(e.message)}finally{setBusy(buttonEl,false)}}
async function replaceKey(event){event.preventDefault();const form=event.currentTarget,id=form.dataset.replaceForm,buttonEl=form.querySelector('button'),status=form.querySelector('.status');setBusy(buttonEl,true,'Replacing…');try{await api('/admin/credentials/'+encodeURIComponent(id)+'/replace-key',{method:'POST',body:JSON.stringify({apiKey:form.apiKey.value,accountId:form.accountId?.value||undefined})});form.apiKey.value='';status.textContent='Key replaced.';status.className='status success';discovered.delete(id);discoveryErrors.delete(id);await refreshCredentialState();await ensureCredentialModels(id,true)}catch(e){status.textContent=e.message;status.className='status error'}finally{setBusy(buttonEl,false)}}
function renderCatalogs(){if(!state)return;const root=document.querySelector('#model-catalogs');root.innerHTML=state.accounts.length?state.accounts.map(catalogCard).join(''):'<div class="empty">Add a credential to discover its available models.</div>';root.querySelectorAll('[data-refresh-catalog]').forEach(btn=>btn.addEventListener('click',()=>ensureCredentialModels(btn.dataset.refreshCatalog,true)))}
function catalogCard(a){const loading=discoveryLoading.has(a.id),error=discoveryErrors.get(a.id),models=discovered.get(a.id);let body;if(loading)body='<div class="catalog-message spinner">Loading model catalog…</div>';else if(error)body='<div class="catalog-message error">'+esc(error)+'</div>';else if(models)body=models.length?'<div class="model-list">'+models.map(modelRow).join('')+'</div>':'<div class="catalog-message">Provider returned no models for this credential.</div>';else body='<div class="catalog-message">Model discovery has not run yet.</div>';return '<article class="catalog" data-catalog-id="'+esc(a.id)+'"><div class="catalog-head"><div><h3>'+esc(identity(a))+'</h3><p>'+esc(providerName(a.provider))+' · '+esc(statusLabel(a.status))+'</p></div><button type="button" class="secondary small" data-refresh-catalog="'+esc(a.id)+'">Refresh</button></div>'+body+'</article>'}
function modelRow(m){const caps=m.capabilities?Object.entries({Vision:m.capabilities.image,Tools:m.capabilities.tools,Streaming:m.capabilities.streaming,Reasoning:m.capabilities.reasoning}).map(([k,v])=>'<span class="cap">'+k+': '+(v?'yes':'no')+'</span>').join(''):'<span class="cap">Capabilities not reported</span>',spec=[m.contextWindow?Number(m.contextWindow).toLocaleString()+' context':null,m.maxOutputTokens?Number(m.maxOutputTokens).toLocaleString()+' max output':null].filter(Boolean).join(' · ')||'Limits not reported';return '<div class="model-row"><div class="model-name">'+esc(m.friendlyName||m.upstreamModelId)+'<span class="model-id">'+esc(m.upstreamModelId)+'</span></div><div class="model-spec">'+esc(spec)+'</div><div class="model-cap">'+caps+'</div></div>'}
async function ensureCredentialModels(id,force=false){if(!state?.accounts.some(a=>a.id===id))return;if(!force&&(discovered.has(id)||discoveryLoading.has(id)||discoveryErrors.has(id)))return;discoveryLoading.add(id);if(force){discovered.delete(id);discoveryErrors.delete(id)}renderCatalogs();try{const result=await api('/admin/credentials/'+encodeURIComponent(id)+'/models');discovered.set(id,Array.isArray(result.models)?result.models:[]);discoveryErrors.delete(id)}catch(e){discoveryErrors.set(id,e.message||'Model discovery failed.')}finally{discoveryLoading.delete(id);renderCatalogs();if(!modelFormDirty)renderRoutes()}}
async function ensureProviderModels(provider,force=false){const accounts=state.accounts.filter(a=>a.provider===provider&&a.status!=='disabled');await Promise.allSettled(accounts.map(a=>ensureCredentialModels(a.id,force)))}
function discoverAll(force){for(const a of state.accounts.filter(a=>a.status!=='disabled'))void ensureCredentialModels(a.id,force)}
async function refreshModels(){const buttonEl=document.querySelector('#refresh-models');setBusy(buttonEl,true,'Refreshing…');try{await Promise.allSettled(state.accounts.filter(a=>a.status!=='disabled').map(a=>ensureCredentialModels(a.id,true)))}finally{setBusy(buttonEl,false)}}
async function saveRoutes(){const buttonEl=document.querySelector('#save-routes'),status=document.querySelector('#route-status');setBusy(buttonEl,true,'Saving…');try{const routes={};for(const slot of slots){const model=document.querySelector('#m-'+slot).value;if(!model)throw new ApiError('Choose a discovered model for '+title(slot)+'.',400,'model_required');routes[slot]={provider:document.querySelector('#p-'+slot).value,model,contextWindow:Number(document.querySelector('#ctx-'+slot).value),maxOutputTokens:Number(document.querySelector('#o-'+slot).value),credentialId:document.querySelector('#c-'+slot).value,vision:readCapability(slot,'vision'),tools:readCapability(slot,'tools'),reasoning:readCapability(slot,'reasoning')}}await api('/admin/model-config',{method:'POST',body:JSON.stringify({routes})});modelFormDirty=false;status.textContent='Routing saved.';status.className='status success';await refreshAll()}catch(e){status.textContent=e.message;status.className='status error'}finally{setBusy(buttonEl,false)}}
async function startOAuth(event){event.preventDefault();const form=event.currentTarget,buttonEl=form.querySelector('button[type=submit]'),status=document.querySelector('#oauth-status');document.querySelector('#oauth-device').classList.add('hidden');setBusy(buttonEl,true,'Starting login…');try{const result=await api('/admin/chatgpt/auth',{method:'POST',body:JSON.stringify({loginMode:form.querySelector('#oauth-mode').value})});activeJobId=result.jobId;status.textContent=result.safeMessage||'Login started.';status.className='status';document.querySelector('#oauth-cancel').classList.remove('hidden');watchAuth(result.jobId)}catch(e){status.textContent=e.message;status.className='status error';setBusy(buttonEl,false)}}
async function watchAuth(jobId){clearTimeout(jobTimer);const status=document.querySelector('#oauth-status'),buttonEl=document.querySelector('#oauth-form button[type=submit]'),cancel=document.querySelector('#oauth-cancel'),device=document.querySelector('#oauth-device'),deviceLink=document.querySelector('#oauth-device-link'),deviceCode=document.querySelector('#oauth-device-code');try{const job=await api('/admin/auth-jobs/'+encodeURIComponent(jobId));if(job.verificationUrl&&job.userCode){deviceLink.href=job.verificationUrl;deviceCode.textContent=job.userCode;device.classList.remove('hidden')}else{device.classList.add('hidden');deviceLink.removeAttribute('href');deviceCode.textContent=''}status.textContent=job.safeError?((job.safeMessage||'Authentication failed')+' '+job.safeError):(job.safeMessage||job.status);status.className='status '+(job.status==='complete'?'success':job.status==='error'?'error':'');if(['complete','error','cancelled'].includes(job.status)){activeJobId=null;cancel.classList.add('hidden');device.classList.add('hidden');deviceLink.removeAttribute('href');deviceCode.textContent='';setBusy(buttonEl,false);if(job.status==='complete')await refreshCredentialState();return}jobTimer=setTimeout(()=>watchAuth(jobId),900)}catch(e){status.textContent=e.message;status.className='status error';setBusy(buttonEl,false)}}
async function cancelOAuth(){if(!activeJobId)return;const buttonEl=document.querySelector('#oauth-cancel');setBusy(buttonEl,true,'Cancelling…');try{await api('/admin/auth-jobs/'+encodeURIComponent(activeJobId)+'/cancel',{method:'POST',body:'{}'});await watchAuth(activeJobId)}catch(e){document.querySelector('#oauth-status').textContent=e.message}finally{setBusy(buttonEl,false)}}
async function addKey(event){event.preventDefault();const buttonEl=event.currentTarget.querySelector('button[type=submit]'),status=document.querySelector('#key-status'),provider=document.querySelector('#key-provider').value,accountId=document.querySelector('#key-account').value.trim();setBusy(buttonEl,true,'Adding…');try{const created=await api('/admin/credentials',{method:'POST',body:JSON.stringify({provider,name:document.querySelector('#key-name').value.trim()||undefined,accountId:provider==='cloudflare'?accountId:undefined,apiKey:document.querySelector('#key-value').value})});document.querySelector('#key-value').value='';status.textContent='Credential added.';status.className='status success';await refreshCredentialState();if(created?.id)await ensureCredentialModels(created.id,true)}catch(e){status.textContent=e.message;status.className='status error'}finally{setBusy(buttonEl,false)}}
function renderProviderControls(){const select=document.querySelector('#key-provider');if(!select||!state)return;const current=select.value;select.innerHTML=(state.providers||[]).filter(p=>p.credentialType==='api-key').map(p=>'<option value="'+esc(p.id)+'">'+esc(p.displayName)+'</option>').join('');if([...select.options].some(o=>o.value===current))select.value=current;syncAccountField()}
function syncAccountField(){const cloudflare=document.querySelector('#key-provider').value==='cloudflare',wrap=document.querySelector('#key-account-wrap'),field=document.querySelector('#key-account');wrap.classList.toggle('hidden',!cloudflare);field.required=cloudflare}
function renderCustomProviders(){const root=document.querySelector('#custom-providers');if(!root||!state)return;const items=(state.providers||[]).filter(p=>p.custom);root.innerHTML=items.length?items.map(customProviderCard).join(''):'<div class="empty">No custom providers configured.</div>';root.querySelectorAll('[data-provider-action]').forEach(btn=>btn.addEventListener('click',()=>providerAction(btn)))}
function customProviderCard(p){return '<article class="credential"><div class="credential-head"><div class="credential-title"><h3>'+esc(p.displayName)+'</h3><p>'+esc(p.id)+' · '+esc(p.apiStyle)+(p.serviceTier?' · service tier '+esc(p.serviceTier):'')+'</p></div></div><div class="credential-line">Models are discovered automatically from credentials for this provider.</div><div class="actions"><button type="button" class="small secondary" data-provider-action="edit" data-id="'+esc(p.id)+'">Edit</button><button type="button" class="small danger" data-provider-action="delete" data-id="'+esc(p.id)+'">Remove</button></div></article>'}
async function addProvider(event){event.preventDefault();const status=document.querySelector('#provider-status'),buttonEl=event.currentTarget.querySelector('button[type=submit]');setBusy(buttonEl,true,'Adding…');try{await api('/admin/providers',{method:'POST',body:JSON.stringify({displayName:document.querySelector('#provider-name').value,baseUrl:document.querySelector('#provider-url').value,apiStyle:document.querySelector('#provider-style').value,serviceTier:document.querySelector('#provider-tier').value.trim()||undefined})});event.currentTarget.reset();status.textContent='Provider added.';status.className='status success';await refreshAll()}catch(e){status.textContent=e.message;status.className='status error'}finally{setBusy(buttonEl,false)}}
async function providerAction(btn){const id=btn.dataset.id,p=providerMeta(id);if(btn.dataset.providerAction==='delete'){if(!confirm('Remove '+p.displayName+'?'))return;try{await api('/admin/providers/'+encodeURIComponent(id),{method:'DELETE',body:'{}'});await refreshAll()}catch(e){alert(e.message)}return}const name=prompt('Display name',p.displayName);if(name===null)return;const baseUrl=prompt('Base URL',p.baseUrl||'');if(baseUrl===null)return;const apiStyle=prompt('API style: chat-completions or responses',p.apiStyle);if(apiStyle===null)return;const serviceTier=prompt('Service tier (optional, e.g. flex)',p.serviceTier||'');if(serviceTier===null)return;try{await api('/admin/providers/'+encodeURIComponent(id),{method:'PATCH',body:JSON.stringify({displayName:name,baseUrl,apiStyle,serviceTier})});await refreshAll()}catch(e){alert(e.message)}}
function relative(value){const ms=Date.parse(value)-Date.now();if(ms<=0)return'now';const m=Math.ceil(ms/60000),h=Math.floor(m/60);return h?('in '+h+'h '+(m%60)+'m'):('in '+m+'m')}
setInterval(()=>document.querySelectorAll('.countdown').forEach(el=>{const value=el.dataset.reset;el.textContent='Ready again '+relative(value)}),30000);
document.querySelector('#save-routes').addEventListener('click',saveRoutes);document.querySelector('#oauth-form').addEventListener('submit',startOAuth);document.querySelector('#key-form').addEventListener('submit',addKey);document.querySelector('#key-provider').addEventListener('change',syncAccountField);document.querySelector('#provider-form').addEventListener('submit',addProvider);document.querySelector('#oauth-cancel').addEventListener('click',cancelOAuth);document.querySelector('#refresh-models').addEventListener('click',refreshModels);document.querySelector('#reload-routes').addEventListener('click',()=>{modelFormDirty=false;document.querySelector('#route-status').textContent='';renderRoutes()});syncAccountField();
const events=new EventSource('/admin/events');['credentials_changed','credential_status_changed','preferred_changed','auth_job_changed','providers_changed'].forEach(type=>events.addEventListener(type,()=>refreshCredentialState().catch(()=>{})));events.addEventListener('model_config_changed',async()=>{const next=await api('/admin/state').catch(()=>null);if(!next)return;state=next;renderSystem();renderCredentials();renderCatalogs();if(modelFormDirty)document.querySelector('#external-change').style.display='block';else renderRoutes()});events.addEventListener('state',event=>{try{const next=JSON.parse(event.data);state=next;pruneDiscovery();renderSystem();renderProviderControls();renderCredentials();renderCustomProviders();renderCatalogs();if(!modelFormDirty)renderRoutes();discoverAll(false);document.querySelector('#gateway-status').textContent='Connected';document.querySelector('#gateway-status').className='status-pill connected'}catch{}});events.onerror=()=>{document.querySelector('#gateway-status').textContent='Reconnecting';document.querySelector('#gateway-status').className='status-pill degraded'};refreshAll().catch(e=>{document.querySelector('#gateway-status').textContent='Unavailable';document.querySelector('#gateway-status').className='status-pill unavailable';document.querySelector('#route-status').textContent=e.message;document.querySelector('#route-status').className='status error'});
})();
</script></body></html>`;
}

function escapeHtml(value: string): string {
  return String(value).replace(/[&<>"']/g, (char) => ({
    "&": "&amp;",
    "<": "&lt;",
    ">": "&gt;",
    '"': "&quot;",
    "'": "&#39;",
  })[char] ?? char);
}
